/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountId = bigint;
export interface DashboardStats {
  'disconnectedCount' : bigint,
  'unreadMessageCount' : bigint,
  'activeCount' : bigint,
  'totalAccounts' : bigint,
}
export interface Message {
  'id' : MessageId,
  'accountId' : AccountId,
  'subject' : string,
  'isStarred' : boolean,
  'preview' : string,
  'platform' : string,
  'isRead' : boolean,
  'sender' : string,
  'timestamp' : bigint,
}
export type MessageId = bigint;
export interface Post {
  'id' : PostId,
  'status' : string,
  'content' : string,
  'createdAt' : bigint,
  'targetAccountIds' : Array<AccountId>,
}
export type PostId = bigint;
export interface SocialMediaAccount {
  'id' : AccountId,
  'status' : string,
  'clientName' : string,
  'lastActivity' : bigint,
  'name' : string,
  'platform' : string,
  'email' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAccount' : ActorMethod<[SocialMediaAccount], AccountId>,
  'createMessage' : ActorMethod<[Message], MessageId>,
  'createPost' : ActorMethod<[Post], PostId>,
  'deleteAccount' : ActorMethod<[AccountId], undefined>,
  'getAccount' : ActorMethod<[AccountId], SocialMediaAccount>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMessage' : ActorMethod<[MessageId], Message>,
  'getPost' : ActorMethod<[PostId], Post>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAccounts' : ActorMethod<[AccountId], Array<SocialMediaAccount>>,
  'listMessages' : ActorMethod<[bigint, bigint], Array<Message>>,
  'listMessagesByAccount' : ActorMethod<[AccountId], Array<Message>>,
  'listPosts' : ActorMethod<[], Array<Post>>,
  'markMessageRead' : ActorMethod<[MessageId, boolean], undefined>,
  'markMessageStarred' : ActorMethod<[MessageId, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateAccountStatus' : ActorMethod<[AccountId, string], undefined>,
  'updatePostStatus' : ActorMethod<[PostId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];