/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccountId = IDL.Nat;
export const SocialMediaAccount = IDL.Record({
  'id' : AccountId,
  'status' : IDL.Text,
  'clientName' : IDL.Text,
  'lastActivity' : IDL.Int,
  'name' : IDL.Text,
  'platform' : IDL.Text,
  'email' : IDL.Text,
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'accountId' : AccountId,
  'subject' : IDL.Text,
  'isStarred' : IDL.Bool,
  'preview' : IDL.Text,
  'platform' : IDL.Text,
  'isRead' : IDL.Bool,
  'sender' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PostId = IDL.Nat;
export const Post = IDL.Record({
  'id' : PostId,
  'status' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'targetAccountIds' : IDL.Vec(AccountId),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'disconnectedCount' : IDL.Nat,
  'unreadMessageCount' : IDL.Nat,
  'activeCount' : IDL.Nat,
  'totalAccounts' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAccount' : IDL.Func([SocialMediaAccount], [AccountId], []),
  'createMessage' : IDL.Func([Message], [MessageId], []),
  'createPost' : IDL.Func([Post], [PostId], []),
  'deleteAccount' : IDL.Func([AccountId], [], []),
  'getAccount' : IDL.Func([AccountId], [SocialMediaAccount], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMessage' : IDL.Func([MessageId], [Message], ['query']),
  'getPost' : IDL.Func([PostId], [Post], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAccounts' : IDL.Func(
      [AccountId],
      [IDL.Vec(SocialMediaAccount)],
      ['query'],
    ),
  'listMessages' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Message)], ['query']),
  'listMessagesByAccount' : IDL.Func(
      [AccountId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'markMessageRead' : IDL.Func([MessageId, IDL.Bool], [], []),
  'markMessageStarred' : IDL.Func([MessageId, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'updateAccountStatus' : IDL.Func([AccountId, IDL.Text], [], []),
  'updatePostStatus' : IDL.Func([PostId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccountId = IDL.Nat;
  const SocialMediaAccount = IDL.Record({
    'id' : AccountId,
    'status' : IDL.Text,
    'clientName' : IDL.Text,
    'lastActivity' : IDL.Int,
    'name' : IDL.Text,
    'platform' : IDL.Text,
    'email' : IDL.Text,
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'accountId' : AccountId,
    'subject' : IDL.Text,
    'isStarred' : IDL.Bool,
    'preview' : IDL.Text,
    'platform' : IDL.Text,
    'isRead' : IDL.Bool,
    'sender' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PostId = IDL.Nat;
  const Post = IDL.Record({
    'id' : PostId,
    'status' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'targetAccountIds' : IDL.Vec(AccountId),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'disconnectedCount' : IDL.Nat,
    'unreadMessageCount' : IDL.Nat,
    'activeCount' : IDL.Nat,
    'totalAccounts' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAccount' : IDL.Func([SocialMediaAccount], [AccountId], []),
    'createMessage' : IDL.Func([Message], [MessageId], []),
    'createPost' : IDL.Func([Post], [PostId], []),
    'deleteAccount' : IDL.Func([AccountId], [], []),
    'getAccount' : IDL.Func([AccountId], [SocialMediaAccount], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMessage' : IDL.Func([MessageId], [Message], ['query']),
    'getPost' : IDL.Func([PostId], [Post], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAccounts' : IDL.Func(
        [AccountId],
        [IDL.Vec(SocialMediaAccount)],
        ['query'],
      ),
    'listMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'listMessagesByAccount' : IDL.Func(
        [AccountId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'markMessageRead' : IDL.Func([MessageId, IDL.Bool], [], []),
    'markMessageStarred' : IDL.Func([MessageId, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'updateAccountStatus' : IDL.Func([AccountId, IDL.Text], [], []),
    'updatePostStatus' : IDL.Func([PostId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };